# Run with:
# docker compose -f examples/aloha_sim/compose.yml up --build
services:
  runtime:
    image: aloha_sim
    depends_on:
      - openpi_server
    build:
      context: ../..
      dockerfile: examples/aloha_sim/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - $PWD:/app
      - ../../data:/data
    # environment:
    #   - HTTP_PROXY=http://127.0.0.1:2340
    #   - HTTPS_PROXY=http://127.0.0.1:2340
    #   - NO_PROXY=localhost,127.0.0.1

  openpi_server:
    image: openpi_server
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - $PWD:/app
      - /hard_disk/OPENPI:/openpi_assets
    environment:
      - SERVER_ARGS
      - OPENPI_DATA_HOME=/openpi_assets
      - IS_DOCKER=true
      # - HTTP_PROXY=http://127.0.0.1:2340
      # - HTTPS_PROXY=http://127.0.0.1:2340
      # - NO_PROXY=localhost,127.0.0.1
    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]